### ISSUE TITLE
Enhancement requests

### ISSUE THREAD

**Issue by tpiotrow** [gallandarakhneorg/afc#26]
I have some requests concerning the new version of AFC:

- Would it be possible to have a common hierarchy for Tuple2D and Shape2D, i.e. making Tuple2D a Shape2D ?

- Can the method turnVector in Vector2D be abstracted to Tuple2D in order to rotate a Point2D ?

- Can the methods setP1 and setP2 be made in Segment2D ?

**Comment by gallandarakhneorg** [comment]
* Impossible to have a hierarchical relationship between `Tuple2D` and `Shape2D`. They are different concepts.
* `turn` cannot be in `Tuple2D` since it is not a string geometrical meaning. I could add turn in `Point2D`.
* `setP1` and `setP2` could be added `Segment2D` with `Point2D` as parameters (not double).

**Comment by tpiotrow** [comment]
Thank you for considering the method setP1/setP2 and making a turn method in Point2D.

As for the common hierarchy I understand Tuple and Shape are not the same concept. I suggested it because the Multishape cannot accept more than one type of object, and thus we cannot have a multishape containing Point2D and Circle2D for example.

**Comment by gallandarakhneorg** [comment]
Since a point has no shape (it is a position), it cannot be a shape . Consequently, it cannot be inside a container of shapes (MultiShape).
I propose to considered the following solutions for solving your problem:
* Creating a new shape type, named `PointShape2afp`, which inherits from `Point2D` and `Shape2afp`.
* Creating a new shape type that is a cloud of points (similar to the `Path2D` but with points only).

Could you discuss with @olivierlamotte for determining the priority between these two approaches.

**Comment by tpiotrow** [comment]
I will discuss it further. Please bear in mind that this is not a issue for the moment but will become one in the next few months.

- I had a naming remark : maybe you can replace "fp" with "d", to contrast with "i", and following that logic the "fx" package could become "dfx" to contrast with "ifx"

**Comment by gallandarakhneorg** [comment]
In the current master, "fp" postfix should not appear any more. It was replaced by "d". For the JavaFX postfix, see #27.

**Comment by gallandarakhneorg** [comment]
The different enhancement requests were added in separate issues: #27, #28, #29, #30, and #31.
This issue may be closed, accordingly.
